files: ^components/omega/
repos:
  - repo: https://github.com/Takishima/cmake-pre-commit-hooks
    rev: v1.9.5
    hooks:
      - id: clang-format
      # - id: clang-tidy
      #   args: [--checks=readability-magic-numbers,--warnings-as-errors=*]
      # - id: cppcheck
      # - id: include-what-you-use

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Can run individually with `pre-commit run isort --all-files`
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--settings-file=components/omega/python_lint.cfg"]

  # Can run individually with `flynt [file]` or `flynt [source]`
  - repo: https://github.com/ikamensh/flynt
    rev: 1.0.1
    hooks:
      - id: flynt
        args: ["--fail-on-change", "--verbose", "--line-length=79"]
        require_serial: true

  # Can run individually with `pre-commit run flake8 --all-files`
  # Need to use flake8 GitHub mirror due to CentOS git issue with GitLab
  # https://github.com/pre-commit/pre-commit/issues/1206
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--config=components/omega/python_lint.cfg"]
        additional_dependencies: [flake8-isort]

  # Can run individually with `pre-commit run mypy --all-files`
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: ["--config=components/omega/python_lint.cfg", "--show-error-codes"]
        verbose: true
        additional_dependencies: ['types-requests']
