name: gh-w

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'mkdocs.yaml'
      - 'docs/**'
      - 'components/*/docs/**'
      - 'components/*/mkdocs.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:

  ci:
    if: ${{ github.repository == 'E3SM-Project/E3SM' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - SMS_D_Ld1_P8.ne4pg2_oQU480.WCYCL2010NS.ghci-oci_gnu
          - ERS_Ld3_P8.ne4pg2_oQU480.WCYCL2010NS.ghci-oci_gnu.allactive-wcprod_1850
    container: 
      image: ghcr.io/e3sm-project/containers-ghci:ghci-0.2.0

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive
      - 
        name: CIME
        working-directory: cime/scripts
        run: |
          ./create_test ${{ matrix.test }} --wait --debug
      - 
        name: Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ matrix.test }}
          path: |
            /projects/e3sm/scratch/${{ matrix.test }}*/TestStatus.log
            /projects/e3sm/scratch/${{ matrix.test }}*/bld/*.bldlog.*
            /projects/e3sm/scratch/${{ matrix.test }}*/run/*.log.*
            /projects/e3sm/scratch/${{ matrix.test }}*/run/*.cprnc.out
