name: gh-w

on:
  pull_request:
    branches: 
      - master
      - maint-3.0
    paths:
      - '!**/docs/**'
      - '!**/mkdocs.yml'
      - '!.github/workflows/**'
      - '.github/workflows/e3sm-gh-ci-w-cime-tests.yml'


  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:

  ci:
    if: ${{ github.repository == 'E3SM-Project/E3SM' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - SMS_D_Ld1_P8.ne4pg2_oQU480.WCYCL2010NS.ghci-oci_gnu
          - ERS_Ld3_P8.ne4pg2_oQU480.WCYCL2010NS.ghci-oci_gnu.allactive-wcprod_1850
    container: 
      image: ghcr.io/e3sm-project/containers-ghci:ghci-0.2.1

    steps:
      - 
        name: Free disk space
        run: |
          echo "Disk space before cleanup:"
          df -h
          echo "Removing large directories using rsync method"
          mkdir -p /opt/empty_dir || true
          for d in \
                   /opt/ghc \
                   /opt/hostedtoolcache \
                   /usr/lib/jvm \
                   /usr/local/.ghcup \
                   /usr/local/lib/android \
                   /usr/local/share/powershell \
                   /usr/share/dotnet \
                   /usr/share/swift \
                   ; do
            rsync --stats -a --delete /opt/empty_dir/ $d || true
          done
          echo "Removing browsers and cleaning up"
          apt-get purge -y -f firefox \
                             google-chrome-stable \
                             microsoft-edge-stable || true
          apt-get autoremove -y > /dev/null 2>&1 || true
          apt-get autoclean -y > /dev/null 2>&1 || true
          echo "Disk space after cleanup:"
          df -h
      - 
        name: Checkout
        uses: actions/checkout@v6
        with:
          show-progress: false
          submodules: recursive
      - 
        name: CIME
        working-directory: cime/scripts
        run: |
          echo "Disk space before test:"
          df -h
          ./create_test ${{ matrix.test }} --wait --debug
          echo "Disk space after test:"
          df -h
      - 
        name: Artifacts
        uses: actions/upload-artifact@v5
        if: ${{ always() }}
        with:
          name: ${{ matrix.test }}
          path: |
            /projects/e3sm/scratch/${{ matrix.test }}*/TestStatus.log
            /projects/e3sm/scratch/${{ matrix.test }}*/bld/*.bldlog.*
            /projects/e3sm/scratch/${{ matrix.test }}*/run/*.log.*
            /projects/e3sm/scratch/${{ matrix.test }}*/run/*.cprnc.out
