name: gh-standalone

on:
  pull_request:
    branches: [ master ]
    paths:
      # first, yes to these
      - '.github/workflows/eamxx-gh-ci-standalone.yml'
      - 'cime_config/machine/config_machines.xml'
      - 'components/eamxx/**'
      - 'components/homme/**'
      # second, no to these
      - '!components/eamxx/docs/**'
      - '!components/eamxx/mkdocs.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:

  ci:
    if: ${{ github.repository == 'E3SM-Project/E3SM' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - sp
          - opt
          - dbg
          - fpe
    container: 
      image: ghcr.io/e3sm-project/containers-standalone-ghci:standalone-ghci-0.1.0

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive
      - 
        name: standalone
        env:
          SHELL: sh
        run: |
          # TODO: get rid of this extra line if we can?
          git config --global safe.directory '*'
          ./components/eamxx/scripts/test-all-scream -m ghci-oci -t ${{ matrix.test }} -c BUILD_SHARED_LIBS=ON
      - 
        name: Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ matrix.test }}
          path: |
            components/eamxx/ctest-build/*/Testing/Temporary/Last*.log
