# This workflow aims to automatically rebuild eamxx documentation
# every time the master branch is updated on github and within every PR

name: EAMxx Docs

on:
  # Runs every time master branch is updated
  push:
    branches: [ master ]
  # Runs every time a PR is open against master
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  emaxx-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          # TODO: git rid of dependency on CIME
          submodules: true
  
      - name: Show action trigger
        run: |
          echo "= The job was automatically triggered by a ${{github.event_name}} event."

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.10"

      - name: Install Python deps
        run: |
          pip install mkdocs pymdown-extensions mkdocs-material mdutils
  
      - name: Generate EAMxx params docs
        working-directory: components/eamxx/scripts
        run: |
          ./eamxx-params-docs-autogen

      - name: Build docs
        working-directory: components/eamxx
        run: |
          mkdocs build --strict --verbose

      # only deploy when there is a push to master
      - if: ${{ github.event_name == 'push' }}
        name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          # information about GITHUB_TOKEN are in settings
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./components/eamxx/site
